### ISSUE TITLE
Wordpress 4.5 Notices

### ISSUE THREAD

**Issue by orionrush** [Chassis/Chassis#171]
Im not actually sure if this is a WP 4.5 issue, as Im new to Cassis, and Vagrant/Puppet in general. But in the wp admin Im receiving some various notices along the lines of:

     http://vagrant.local/wp/wp-admin/plugins.php

     Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the support forums. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /vagrant/wp/wp-includes/update.php on line 306

So after a bit of digging, I found this post:
http://ryansechrest.com/2014/08/wordpress-establish-secure-connection-wordpress-org/

Ryan suggest editing your host file, or your puppet config to include wordpress.org as a new host. So I added this as a mighty convenient [Chassis Extension](http://docs.chassis.io/en/latest/extend/):
     # Enable WP to connect to Wordpress.org
     
     host { "api.wordpress.org":
         ip => "66.155.40.202",
     }

One `vagrant provision` later and everything works a treat. Should perhaps these lines make their way into the main puppet recipe?

**Comment by orionrush** [comment]
Would that edit be best added here?

[`Chassis/puppet/modules/chassis/manifests/hosts.pp`](https://github.com/orionrush/Chassis/blob/master/puppet/modules/chassis/manifests/hosts.pp)

**Comment by rmccue** [comment]
This error message means that your Vagrant box can't do DNS lookups properly, so it's actually symptomatic of a larger issue. From what I've seen, this occurs when you change which network the host is connected to (i.e. laptop connecting to a different network), usually fixed by restarting your box (`vagrant reload`). Defining these lines in Chassis overrides the DNS lookup, which masks the problem, but other external requests will continue to fail, so I'd rather we leave it broken if we can't fix it fully. At least it's obvious then.

**Comment by orionrush** [comment]
Is this only an issue with my particular setup? `vagrant reload` doesn't resolve the DNS issues. I didn't mention it but another issue was that everything with the box was very very slow.

After some more searches I found that other Vagrant users were having similar issues with various boxes. The general slowness is related to the  network connections that the box is provisioned with. In my case the connections are so slow that WordPress is timing them out before a connection is established. 

After some searching I found this addition to the Vagrant file that has radically improved performance, and resolved all the connectivity errors that WP was throwing:  https://github.com/mitchellh/vagrant/issues/1807
	
```
config.vm.provider :virtualbox do |vb|
	vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
	vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
end
```
